version: '3.3'
services:
  mysql:
    container_name: card_mysql
    restart: always
    image: mysql:latest
    command: mysqld --user=root
    volumes:
      - ./DbScript.sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: Card
    ports:
      - 3306:3306

